spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/bts?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
  application:
    name: bts
  liquibase:
    change-log: classpath:liquibase/master.xml
    contexts: "develop"